




# Importing data set

In [1]:
# Importing pandas and numpy libraries
import pandas as pd
import numpy as np

# Loading our csv data set
df = pd.read_csv('/content/Autolib_dataset (2).csv')
# Looking at the first 5 rows of our data frame
df.head()

Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue Eugène Oudiné     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

In [2]:
# Accessing the information about our data 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64 
 2   Bluecar counter      5000 non-null   int64 
 3   Utilib counter       5000 non-null   int64 
 4   Utilib 1.4 counter   5000 non-null   int64 
 5   Charge Slots         5000 non-null   int64 
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64 
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots 

In [3]:
# Looking at the shape of our data set
df.shape

(5000, 25)

# Cleaning our data

**VALIDATING OUR DATA**

In [4]:
# dropping columns we do not need for analysis
df.drop(['Geo point','Scheduled at','Displayed comment','ID'], axis = 1,inplace = True)

In [5]:
# Checking if the columns have been dropped
# ---
df.head()

Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue Eugène Oudiné     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 21 columns]

**COMPLETENESS**

In [6]:
# Changing the cases for columns to lower case & renaming my columns
df.columns = map(str.lower,df.columns)
columns = ['address','cars','bluecar','utilib','utilib_1.4','charge slots','charging status',
           'city','kind','postal code','pubic name','rental status','slots','station type','status','subscription status',
           'year','month','day','hour','minute']
df.columns = columns
df.columns

Index(['address', 'cars', 'bluecar', 'utilib', 'utilib_1.4', 'charge slots',
       'charging status', 'city', 'kind', 'postal code', 'pubic name',
       'rental status', 'slots', 'station type', 'status',
       'subscription status', 'year', 'month', 'day', 'hour', 'minute'],
      dtype='object')

In [7]:
#renaming column name 
df.rename(columns={'pubic name':'public name'}, inplace=True)

In [8]:
# Checking my data frame
df.head()

address  cars  bluecar  ...  day  hour  minute
0                 2 Avenue de Suffren     0        0  ...    8    11      43
1           145 Rue Raymond Losserand     6        6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3        3  ...    3    20      14
3              51 Rue Eugène Oudiné     3        3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3        3  ...    8    17      23

[5 rows x 21 columns]

**CONSISTENCY**

In [9]:
# Check for missing values
df.isnull().sum()

address                0
cars                   0
bluecar                0
utilib                 0
utilib_1.4             0
charge slots           0
charging status        0
city                   0
kind                   0
postal code            0
public name            0
rental status          0
slots                  0
station type           0
status                 0
subscription status    0
year                   0
month                  0
day                    0
hour                   0
minute                 0
dtype: int64

In [10]:
# Checking for duplicated values
df.duplicated().sum()

0

**ACCURACY**

In [11]:
# Checking if number of cars is equal to the number of blue cars
car_equal = df['cars'] == df['bluecar']
cond_list = [car_equal]

option = [True]

# Create a column and conditional statement with numpy select() function
df['list_equal']= np.select(cond_list, option, default='False')

df['list_equal'].unique()


array(['True'], dtype=object)

In [12]:
#dropping column cars because the two columns(bluecar) are equal 
df.drop('cars',axis = 1,inplace = True)


In [13]:
df.head()

address  bluecar  utilib  ...  hour  minute list_equal
0                 2 Avenue de Suffren        0       0  ...    11      43       True
1           145 Rue Raymond Losserand        6       0  ...     7      24       True
2    2 Avenue John Fitzgerald Kennedy        3       0  ...    20      14       True
3              51 Rue Eugène Oudiné        3       1  ...     4      37       True
4  6 avenue de la Porte de Champerret        3       0  ...    17      23       True

[5 rows x 21 columns]

In [14]:
# Checking if charging status when 'future' the blue couter car is equal to zero
condition = [(df['charging status'] == 'future') & (df['bluecar']== 0)]

# Create a column and conditional statement with numpy select() function
df['charge_blue'] = np.select(condition,[True], default='False')

df['charge_blue'].unique()

array(['False'], dtype=object)

In [15]:
# Checking if charging status column has future status
df['charging status'].unique()

array(['nonexistent', 'operational', 'broken'], dtype=object)

In [16]:
# Checking if station type subs center status is in the data
df['station type'].unique()

array(['station', 'full_station', 'subs_center'], dtype=object)

In [17]:
# dropping columns created while checking accuracy
df.drop(['list_equal','charge_blue'],axis = 1,inplace = True)


In [18]:
df.head()

address  bluecar  utilib  ...  day  hour minute
0                 2 Avenue de Suffren        0       0  ...    8    11     43
1           145 Rue Raymond Losserand        6       0  ...    6     7     24
2    2 Avenue John Fitzgerald Kennedy        3       0  ...    3    20     14
3              51 Rue Eugène Oudiné        3       1  ...    4     4     37
4  6 avenue de la Porte de Champerret        3       0  ...    8    17     23

[5 rows x 20 columns]

In [19]:
# Creating a bluecar and utilib and utilib 4 column with diff()
df['bluecar_rental'] = df['bluecar'].diff()
df['utilib_rental'] = df['utilib'].diff()
df['utilib1.4_rental'] = df['utilib_1.4'].diff()


In [20]:
df.head(5)

address  bluecar  ...  utilib_rental  utilib1.4_rental
0                 2 Avenue de Suffren        0  ...            NaN               NaN
1           145 Rue Raymond Losserand        6  ...            0.0               0.0
2    2 Avenue John Fitzgerald Kennedy        3  ...            0.0               2.0
3              51 Rue Eugène Oudiné        3  ...            1.0              -2.0
4  6 avenue de la Porte de Champerret        3  ...           -1.0               0.0

[5 rows x 23 columns]

# Analysis

**BLUE CAR**

In [21]:
#get unique values fo column bluecar rental
df.bluecar_rental.unique()

array([nan,  6., -3.,  0.,  3., -2.,  5., -6.,  1.,  4., -5., -1.,  2.,
       -4.,  7., -7.])

In [22]:
# Identify the most popular hour of the day for picking up a shared electric car 
# (Bluecar) in the city of Paris over the month of April 2018.

# The use of blucar renatl diff < 0 because at this point is where the number of
# cars was less so a car was taken
conditions = (df['month']==4) & (df['year']==2018) & (df['city']=='Paris')&(df['bluecar_rental'] < 0)

popular_hour = df[conditions].groupby('hour')['hour'].count().sort_values(ascending = False)
popular_hour.head(1)

hour
21    80
Name: hour, dtype: int64

In [23]:
# What is the most popular hour for returning cars?
# Use of bluecar rental where diff was > 0 meaning that is the time most cars are returned
conditions = df['bluecar_rental'] > 0 

popular_hour = df[conditions].groupby('hour')['hour'].count().sort_values(ascending = False)
popular_hour.head(1)

hour
6    101
Name: hour, dtype: int64

In [24]:
# What station is the most popular?
# Overall?
station = df[(df['kind']== 'STATION') & (df['status']=='ok')].groupby('public name')['public name'].count().sort_values(ascending = False)
station.head(1)

public name
Paris/Porte de Montrouge/8    13
Name: public name, dtype: int64

In [25]:
# At the most popular picking hour?
hour = df[(df['kind']== 'STATION') & (df['status']=='ok')&(df['hour']==21)].groupby('public name')['public name'].count().sort_values(ascending = False)
hour.head(1)

public name
Paris/Tronchet/19    4
Name: public name, dtype: int64

In [26]:
#What postal code is the most popular for picking up Blue cars? 
postal = df[df['bluecar_rental'] < 0].groupby('postal code')['postal code'].count().sort_values(ascending = False)
postal.head(1)

postal code
75015    116
Name: postal code, dtype: int64

In [27]:
#Does the most popular station belong to that postal code? overall?
station = df[df['postal code']== 75015].groupby('public name')['postal code'].count().sort_values(ascending = False)
station.head(1)

public name
Paris/Grenelle 31/Parking    11
Name: postal code, dtype: int64

In [43]:
#At the most popular picking hour?
station_hour =  df[df['hour']==21].groupby('postal code')['public name'].count().sort_values(ascending=False)
station_hour.head(1)

postal code
75014    16
Name: public name, dtype: int64

**UTILIB**

In [29]:
df.utilib_rental.unique()

array([nan,  0.,  1., -1.,  2., -2.])

In [30]:
# Identify the most popular hour of the day for picking up a shared electric car 
# utilib in the city of Paris over the month of April 2018.

# The use of utilib renatl diff < 0 because at this point is where the number of
# cars was less so a car was taken
conditions = (df['month']==4) & (df['year']==2018) & (df['city']=='Paris')&(df['utilib_rental'] < 0)

popular_hour = df[conditions].groupby('hour')['hour'].count().sort_values(ascending = False)
popular_hour.head(1)

hour
19    12
Name: hour, dtype: int64

In [31]:
# What is the most popular hour for returning cars?
# Use of Utilib rental where diff was > 0 meaning that is the time most cars are returned
conditions = df['utilib_rental'] > 0 

popular_hour = df[conditions].groupby('hour')['hour'].count().sort_values(ascending = False)
popular_hour.head(1)

hour
5    17
Name: hour, dtype: int64

In [32]:
# What station is the most popular?
# Overall?
station = df[(df['kind']== 'STATION') & (df['status']=='ok')].groupby('public name')['public name'].count().sort_values(ascending = False)
station.head(1)

public name
Paris/Porte de Montrouge/8    13
Name: public name, dtype: int64

In [33]:
# At the most popular picking hour?
hour = df[(df['kind']== 'STATION') & (df['status']=='ok')&(df['hour']==19)].groupby('public name')['public name'].count().sort_values(ascending = False)
hour.head(1)

public name
Alfortville/Port à l'Anglais/39    2
Name: public name, dtype: int64

In [34]:
#What postal code is the most popular for picking up Blue cars? #Does the most popular station belong to that postal code? 
postal = df[df['utilib_rental'] < 0].groupby('postal code')['public name'].count().sort_values(ascending = False)
postal.head(1)

postal code
75015    22
Name: public name, dtype: int64

In [44]:
#At the most popular picking hour?
station_hour =  df[df['hour']==19].groupby('postal code')['public name'].count().sort_values(ascending=False)
station_hour.head(1)

postal code
75017    11
Name: public name, dtype: int64

UTILIB **1.4**

In [36]:
df['utilib1.4_rental'].unique()

array([nan,  0.,  2., -2.,  1., -1.,  3., -3.])

In [37]:
# Identify the most popular hour of the day for picking up a shared electric car 
# utilib 1.4 in the city of Paris over the month of April 2018.

# The use of utilib renatl diff < 0 because at this point is where the number of
# cars was less so a car was taken
conditions = (df['month']==4) & (df['year']==2018) & (df['city']=='Paris')&(df['utilib1.4_rental'] < 0)

popular_hour = df[conditions].groupby('hour')['hour'].count().sort_values(ascending = False)
popular_hour.head(1)

hour
3    20
Name: hour, dtype: int64

In [38]:
# What is the most popular hour for returning cars?
# Use of Utilib 1.4 rental where diff was > 0 meaning that is the time most cars are returned
conditions = df['utilib1.4_rental'] > 0 

popular_hour = df[conditions].groupby('hour')['hour'].count().sort_values(ascending = False)
popular_hour.head(1)

hour
3    30
Name: hour, dtype: int64

In [39]:
# What station is the most popular?
# Overall?
station = df[(df['kind']== 'STATION') & (df['status']=='ok')].groupby('public name')['public name'].count().sort_values(ascending = False)
station.head(1)

public name
Paris/Porte de Montrouge/8    13
Name: public name, dtype: int64

In [40]:
# At the most popular picking hour?
hour = df[(df['kind']== 'STATION') & (df['status']=='ok')&(df['hour']==3)].groupby('public name')['public name'].count().sort_values(ascending = False)
hour.head(1)

public name
Paris/Julien Lacroix/39    2
Name: public name, dtype: int64

In [41]:
#What postal code is the most popular for picking up Blue cars? #Does the most popular station belong to that postal code? 
postal = df[df['utilib1.4_rental'] < 0].groupby('postal code')['public name'].count().sort_values(ascending = False)
postal.head(1)

postal code
75015    35
Name: public name, dtype: int64

In [45]:
#At the most popular picking hour?
station_hour =  df[df['hour']==3].groupby('postal code')['public name'].count().sort_values(ascending=False)
station_hour.head(1)

postal code
75016    15
Name: public name, dtype: int64